// Code generated by "stringer -output=itun_gen.go -trimprefix=Proto -type=Proto"; DO NOT EDIT.

package itun

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMP-1]
	_ = x[TCP-6]
	_ = x[UDP-17]
}

const (
	_Proto_name_0 = "ICMP"
	_Proto_name_1 = "TCP"
	_Proto_name_2 = "UDP"
)

func (i Proto) String() string {
	switch {
	case i == 1:
		return _Proto_name_0
	case i == 6:
		return _Proto_name_1
	case i == 17:
		return _Proto_name_2
	default:
		return "Proto(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
