// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: control.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// todo: 无用
type MgrType int32

const (
	MgrType_enum_start      MgrType = 0
	MgrType_MgrSegCrypto    MgrType = 1
	MgrType_MgrSegIPv6      MgrType = 2
	MgrType_MgrSegEndConfig MgrType = 3
	MgrType_MgrSegAddTCP    MgrType = 4
	MgrType_MgrSegDelTCP    MgrType = 5
	MgrType_MgrSegAddUDP    MgrType = 6
	MgrType_MgrSegDelUDP    MgrType = 7
	MgrType_MgrSegPackLoss  MgrType = 8
	MgrType_MgrSegPing      MgrType = 9
	MgrType_enum_end        MgrType = 10
)

// Enum value maps for MgrType.
var (
	MgrType_name = map[int32]string{
		0:  "enum_start",
		1:  "MgrSegCrypto",
		2:  "MgrSegIPv6",
		3:  "MgrSegEndConfig",
		4:  "MgrSegAddTCP",
		5:  "MgrSegDelTCP",
		6:  "MgrSegAddUDP",
		7:  "MgrSegDelUDP",
		8:  "MgrSegPackLoss",
		9:  "MgrSegPing",
		10: "enum_end",
	}
	MgrType_value = map[string]int32{
		"enum_start":      0,
		"MgrSegCrypto":    1,
		"MgrSegIPv6":      2,
		"MgrSegEndConfig": 3,
		"MgrSegAddTCP":    4,
		"MgrSegDelTCP":    5,
		"MgrSegAddUDP":    6,
		"MgrSegDelUDP":    7,
		"MgrSegPackLoss":  8,
		"MgrSegPing":      9,
		"enum_end":        10,
	}
)

func (x MgrType) Enum() *MgrType {
	p := new(MgrType)
	*p = x
	return p
}

func (x MgrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MgrType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (MgrType) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x MgrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MgrType.Descriptor instead.
func (MgrType) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Bool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_control_proto protoreflect.FileDescriptor

var file_control_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x75, 0x6c,
	0x6c, 0x22, 0x1c, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a,
	0xca, 0x01, 0x0a, 0x07, 0x4d, 0x67, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x65,
	0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d,
	0x67, 0x72, 0x53, 0x65, 0x67, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x4d, 0x67, 0x72, 0x53, 0x65, 0x67, 0x49, 0x50, 0x76, 0x36, 0x10, 0x02, 0x12, 0x13, 0x0a,
	0x0f, 0x4d, 0x67, 0x72, 0x53, 0x65, 0x67, 0x45, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x67, 0x72, 0x53, 0x65, 0x67, 0x41, 0x64, 0x64, 0x54,
	0x43, 0x50, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x67, 0x72, 0x53, 0x65, 0x67, 0x44, 0x65,
	0x6c, 0x54, 0x43, 0x50, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x67, 0x72, 0x53, 0x65, 0x67,
	0x41, 0x64, 0x64, 0x55, 0x44, 0x50, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x67, 0x72, 0x53,
	0x65, 0x67, 0x44, 0x65, 0x6c, 0x55, 0x44, 0x50, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x67,
	0x72, 0x53, 0x65, 0x67, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x73, 0x73, 0x10, 0x08, 0x12, 0x0e,
	0x0a, 0x0a, 0x4d, 0x67, 0x72, 0x53, 0x65, 0x67, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x09, 0x12, 0x0c,
	0x0a, 0x08, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x65, 0x6e, 0x64, 0x10, 0x0a, 0x32, 0x5f, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x12, 0x0e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x42, 0x6f, 0x6f,
	0x6c, 0x1a, 0x0e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x04, 0x49, 0x50, 0x76, 0x36, 0x12, 0x0e, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x0e, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x00, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x73, 0x53,
	0x68, 0x75, 0x62, 0x2f, 0x69, 0x74, 0x75, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData = file_control_proto_rawDesc
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_proto_rawDescData)
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_control_proto_goTypes = []interface{}{
	(MgrType)(0), // 0: internal.MgrType
	(*Null)(nil), // 1: internal.Null
	(*Bool)(nil), // 2: internal.Bool
}
var file_control_proto_depIdxs = []int32{
	2, // 0: internal.Control.crypto:input_type -> internal.Bool
	1, // 1: internal.Control.IPv6:input_type -> internal.Null
	1, // 2: internal.Control.crypto:output_type -> internal.Null
	2, // 3: internal.Control.IPv6:output_type -> internal.Bool
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_rawDesc = nil
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
