// Code generated by "stringer -output gob_gen.go -trimprefix=CtrType -type=CtrType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[start-0]
	_ = x[InitConfig-1]
	_ = x[AddSession-2]
	_ = x[DelSession-3]
	_ = x[PackLoss-4]
	_ = x[Ping-5]
	_ = x[end-6]
}

const _CtrType_name = "startInitConfigAddSessionDelSessionPackLossPingend"

var _CtrType_index = [...]uint8{0, 5, 15, 25, 35, 43, 47, 50}

func (i CtrType) String() string {
	if i >= CtrType(len(_CtrType_index)-1) {
		return "CtrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CtrType_name[_CtrType_index[i]:_CtrType_index[i+1]]
}
