// Code generated by "stringer -output=mgrset_gen.go -trimprefix=MgrSeg -type=MgrSegType"; DO NOT EDIT.

package segment

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[enum_start-0]
	_ = x[Crypto-1]
	_ = x[IPv6-2]
	_ = x[EndConfig-3]
	_ = x[AddTCP-4]
	_ = x[DelTCP-5]
	_ = x[AddUDP-6]
	_ = x[DelUDP-7]
	_ = x[PackLoss-8]
	_ = x[Ping-9]
	_ = x[enum_end-10]
}

const _MgrSegType_name = "enum_startCryptoIPv6EndConfigAddTCPDelTCPAddUDPDelUDPPackLossPingenum_end"

var _MgrSegType_index = [...]uint8{0, 10, 16, 20, 29, 35, 41, 47, 53, 61, 65, 73}

func (i MgrSegType) String() string {
	if i >= MgrSegType(len(_MgrSegType_index)-1) {
		return "MgrSegType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MgrSegType_name[_MgrSegType_index[i]:_MgrSegType_index[i+1]]
}
