// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: mgrseg.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// req
type CryptoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crypto bool `protobuf:"varint,1,opt,name=Crypto,proto3" json:"Crypto,omitempty"`
}

func (x *CryptoReq) Reset() {
	*x = CryptoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoReq) ProtoMessage() {}

func (x *CryptoReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoReq.ProtoReflect.Descriptor instead.
func (*CryptoReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoReq) GetCrypto() bool {
	if x != nil {
		return x.Crypto
	}
	return false
}

type IPv6Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IPv6Req) Reset() {
	*x = IPv6Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPv6Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Req) ProtoMessage() {}

func (x *IPv6Req) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Req.ProtoReflect.Descriptor instead.
func (*IPv6Req) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{1}
}

type EndConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndConfigReq) Reset() {
	*x = EndConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndConfigReq) ProtoMessage() {}

func (x *EndConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndConfigReq.ProtoReflect.Descriptor instead.
func (*EndConfigReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{2}
}

type AddTCPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *AddTCPReq) Reset() {
	*x = AddTCPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTCPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTCPReq) ProtoMessage() {}

func (x *AddTCPReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTCPReq.ProtoReflect.Descriptor instead.
func (*AddTCPReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{3}
}

func (x *AddTCPReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type DelTCPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *DelTCPReq) Reset() {
	*x = DelTCPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTCPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTCPReq) ProtoMessage() {}

func (x *DelTCPReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTCPReq.ProtoReflect.Descriptor instead.
func (*DelTCPReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{4}
}

func (x *DelTCPReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type AddUDPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *AddUDPReq) Reset() {
	*x = AddUDPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUDPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUDPReq) ProtoMessage() {}

func (x *AddUDPReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUDPReq.ProtoReflect.Descriptor instead.
func (*AddUDPReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{5}
}

func (x *AddUDPReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type DelUDPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *DelUDPReq) Reset() {
	*x = DelUDPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUDPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUDPReq) ProtoMessage() {}

func (x *DelUDPReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUDPReq.ProtoReflect.Descriptor instead.
func (*DelUDPReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{6}
}

func (x *DelUDPReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type PackLossReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PackLossReq) Reset() {
	*x = PackLossReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackLossReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackLossReq) ProtoMessage() {}

func (x *PackLossReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackLossReq.ProtoReflect.Descriptor instead.
func (*PackLossReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{7}
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{8}
}

// resp
type CryptoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CryptoResp) Reset() {
	*x = CryptoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoResp) ProtoMessage() {}

func (x *CryptoResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoResp.ProtoReflect.Descriptor instead.
func (*CryptoResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{9}
}

type IPv6Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IPv6 bool `protobuf:"varint,1,opt,name=IPv6,proto3" json:"IPv6,omitempty"`
}

func (x *IPv6Resp) Reset() {
	*x = IPv6Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPv6Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Resp) ProtoMessage() {}

func (x *IPv6Resp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Resp.ProtoReflect.Descriptor instead.
func (*IPv6Resp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{10}
}

func (x *IPv6Resp) GetIPv6() bool {
	if x != nil {
		return x.IPv6
	}
	return false
}

type EndConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndConfigResp) Reset() {
	*x = EndConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndConfigResp) ProtoMessage() {}

func (x *EndConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndConfigResp.ProtoReflect.Descriptor instead.
func (*EndConfigResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{11}
}

type AddTCPResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID uint32 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *AddTCPResp) Reset() {
	*x = AddTCPResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTCPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTCPResp) ProtoMessage() {}

func (x *AddTCPResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTCPResp.ProtoReflect.Descriptor instead.
func (*AddTCPResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{12}
}

func (x *AddTCPResp) GetSessionID() uint32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *AddTCPResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DelTCPResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *DelTCPResp) Reset() {
	*x = DelTCPResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTCPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTCPResp) ProtoMessage() {}

func (x *DelTCPResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTCPResp.ProtoReflect.Descriptor instead.
func (*DelTCPResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{13}
}

func (x *DelTCPResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddUDPResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID uint32 `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *AddUDPResp) Reset() {
	*x = AddUDPResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUDPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUDPResp) ProtoMessage() {}

func (x *AddUDPResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUDPResp.ProtoReflect.Descriptor instead.
func (*AddUDPResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{14}
}

func (x *AddUDPResp) GetSessionID() uint32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *AddUDPResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DelUDPResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *DelUDPResp) Reset() {
	*x = DelUDPResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelUDPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUDPResp) ProtoMessage() {}

func (x *DelUDPResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUDPResp.ProtoReflect.Descriptor instead.
func (*DelUDPResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{15}
}

func (x *DelUDPResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PackLossResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PL float32 `protobuf:"fixed32,1,opt,name=PL,proto3" json:"PL,omitempty"`
}

func (x *PackLossResp) Reset() {
	*x = PackLossResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackLossResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackLossResp) ProtoMessage() {}

func (x *PackLossResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackLossResp.ProtoReflect.Descriptor instead.
func (*PackLossResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{16}
}

func (x *PackLossResp) GetPL() float32 {
	if x != nil {
		return x.PL
	}
	return 0
}

type PingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mgrseg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_mgrseg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_mgrseg_proto_rawDescGZIP(), []int{17}
}

var File_mgrseg_proto protoreflect.FileDescriptor

var file_mgrseg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x67, 0x72, 0x73, 0x65, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x23, 0x0a, 0x09, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x22, 0x09, 0x0a,
	0x07, 0x49, 0x50, 0x76, 0x36, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x54,
	0x43, 0x50, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x54, 0x43, 0x50, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x55, 0x44, 0x50, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x44,
	0x65, 0x6c, 0x55, 0x44, 0x50, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x0d, 0x0a, 0x0b,
	0x50, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x22, 0x09, 0x0a, 0x07, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x1e, 0x0a, 0x08, 0x49, 0x50, 0x76, 0x36, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x49, 0x50, 0x76, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x49, 0x50, 0x76, 0x36, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x40, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x54, 0x43, 0x50, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x22, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x54, 0x43,
	0x50, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x40, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x55, 0x44, 0x50, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x22, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x55, 0x44, 0x50, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x1e, 0x0a, 0x0c, 0x50, 0x61, 0x63, 0x6b, 0x4c, 0x6f, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x50, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x50,
	0x4c, 0x22, 0x0a, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x73, 0x53,
	0x68, 0x75, 0x62, 0x2f, 0x69, 0x74, 0x75, 0x6e, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mgrseg_proto_rawDescOnce sync.Once
	file_mgrseg_proto_rawDescData = file_mgrseg_proto_rawDesc
)

func file_mgrseg_proto_rawDescGZIP() []byte {
	file_mgrseg_proto_rawDescOnce.Do(func() {
		file_mgrseg_proto_rawDescData = protoimpl.X.CompressGZIP(file_mgrseg_proto_rawDescData)
	})
	return file_mgrseg_proto_rawDescData
}

var file_mgrseg_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_mgrseg_proto_goTypes = []interface{}{
	(*CryptoReq)(nil),     // 0: internal.CryptoReq
	(*IPv6Req)(nil),       // 1: internal.IPv6Req
	(*EndConfigReq)(nil),  // 2: internal.EndConfigReq
	(*AddTCPReq)(nil),     // 3: internal.AddTCPReq
	(*DelTCPReq)(nil),     // 4: internal.DelTCPReq
	(*AddUDPReq)(nil),     // 5: internal.AddUDPReq
	(*DelUDPReq)(nil),     // 6: internal.DelUDPReq
	(*PackLossReq)(nil),   // 7: internal.PackLossReq
	(*PingReq)(nil),       // 8: internal.PingReq
	(*CryptoResp)(nil),    // 9: internal.CryptoResp
	(*IPv6Resp)(nil),      // 10: internal.IPv6Resp
	(*EndConfigResp)(nil), // 11: internal.EndConfigResp
	(*AddTCPResp)(nil),    // 12: internal.AddTCPResp
	(*DelTCPResp)(nil),    // 13: internal.DelTCPResp
	(*AddUDPResp)(nil),    // 14: internal.AddUDPResp
	(*DelUDPResp)(nil),    // 15: internal.DelUDPResp
	(*PackLossResp)(nil),  // 16: internal.PackLossResp
	(*PingResp)(nil),      // 17: internal.PingResp
}
var file_mgrseg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mgrseg_proto_init() }
func file_mgrseg_proto_init() {
	if File_mgrseg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mgrseg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPv6Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTCPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTCPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUDPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUDPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackLossReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPv6Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTCPResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTCPResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUDPResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelUDPResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackLossResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mgrseg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mgrseg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mgrseg_proto_goTypes,
		DependencyIndexes: file_mgrseg_proto_depIdxs,
		MessageInfos:      file_mgrseg_proto_msgTypes,
	}.Build()
	File_mgrseg_proto = out.File
	file_mgrseg_proto_rawDesc = nil
	file_mgrseg_proto_goTypes = nil
	file_mgrseg_proto_depIdxs = nil
}
